/*
 * USART.c

 *
 *  Created on: 15/2/2020
 *      Author: ABBAS SALAH HATATA
 */

/******************************************INCLUDE_LIBERARY******************************************/
#include "USART.h"


/******************************************FUNCTION_OPERATION****************************************/
// INIT FUNCTION OF USART
void INIT_USART(void){

	// ENABEL TRANSMITTER & RECEIVER		(UCSRB_REG|=(1<<4)|(1<<3)) "WRITE 1 IN BIT 3&4"

	SET_BIT(UCSRB_REG,0x04);
	SET_BIT(UCSRB_REG,0x03);
	//SET FRAME FORMATE:8_DATABIT ,1_STOPBIT, 0_PARITY    (UCSRC_REG |=(1<<2)|(1<<1))  "WRITE 1 IN BIT 2&1"

	SET_BIT(UCSRC_REG,0x07);    //URSEL_REG
	SET_BIT(UCSRC_REG,0x01);    //SELECT 8_BIT DATA IN FRAME FORMATE
	SET_BIT(UCSRC_REG,0x02);	//SELECT 8_BIT DATA IN FRAME FORMATE

	//SET_BAUD_RATE
	UBRRL_REG = BAUD_PRESCALE; // SEND LOW 8_BIT IN UBRR
	UBRRH_REG = (BAUD_PRESCALE >> 0x08); // SEND HIGH 8_BIT IN UBRR

	/*FOR EXPLAINING*/
	CLEAR_BIT(UCSRB_REG,0x02);  //BY DEFEULT IS ZERO REG_STOP_BIT
	CLEAR_BIT(UCSRC_REG,0x03);  //BY DEFEULT IS ZERO REG_STOP_BIT
	CLEAR_BIT(UCSRC_REG,0x04);  //BY DEFEULT IS ZERO REG_PARITY_FLAG
	CLEAR_BIT(UCSRC_REG,0x05);  //BY DEFEULT IS ZERO REG_PARITY_FLAG
	CLEAR_BIT(UCSRC_REG,0x06);  //BY DEFEULT IS ZERO REG_TO_DETERMINED ASYN OR SYN MODE
}



//TRANSMITTE DATA
void TRANSMITER_USART(uint8  DATA){


	//WAIT FOR EMPTY TRANSMITTE BUFFER
while(!(UCSRA_REG & (1<<0x05))){

	/*DO_NOTHING*/
  };
//PUT DATA INTO THE BUFFER AND SEND DATA
	UDR_REG=DATA;
}



//RECEIVER DATA

uint8 RECEIVER_USART(){
// WAIT FOR DATA BE RECEIVED
	while ((UCSRA_REG &(1<<0x07))== 0){
		/*DO N0THING*/
	};
//RETEURN DATA
	return UDR_REG;


}


//FLUSHER USART
void FLUSHER_USART(void){

//HOLDER DATA
	uint8 DUMMEY;
//WHILE BE FLUSH WHEN THE RECEIVER IS DISABLED
 while (UCSRA_REG & (1<<0x07))DUMMEY =UDR_REG;

}

//TRANSIMETTER THE STRING
void TRANSMITTER_STRING_USART (uint8 *STRING){

	uint8 INDEX =0;
	while (STRING[INDEX]!=0){
		TRANSMITER_USART(STRING[INDEX]);
		INDEX++;
	}

}


//READ_ACSSES_UCSRC_REG
uint8 USART_READUCSRC (void){


	uint8 ucsrc;
	/*read ucsrc*/
	ucsrc = UBRRH_REG;
	ucsrc = UCSRC_REG;
	return ucsrc ;

}

